services:
  - type: web
    name: inventory-system
    env: php
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: DATABASE_URL
        sync: false